### ISSUE TITLE
Add user mapping

### ISSUE THREAD

**Issue by gyscos** [redmine-gitlab-migrator/redmine-gitlab-migrator#19]
Sometimes, having exact username match is not an option when migrating.
It would be nice to have the option of specifying a user mapping file to get the gitlab username for each redmine account - something like the [authorsFile](https://git-scm.com/docs/git-svn#git-svn---authors-fileltfilenamegt) in git-svn.

**Comment by scambra** [comment]
I added user-dict option to my fork: https://github.com/Programatica/redmine-gitlab-migrator

It reads a yaml file mapping redmine username to gitlab username

**Comment by mzabielski** [comment]
@scambra I have a few questions connected with your fork:

- How this users YAML file should look like? Could you provide some example?
- How can I install your fork instead of using origin one? I'm a Python newbie, so maybe it's a silly question :)

**Comment by scambra** [comment]
It's a YAML file with key value pairs:

```
---
redmine_username: gitlab_username
```

Clone repository and Install with this command:
python setup.py install

Run as root or prefix command with sudo

**Comment by mzabielski** [comment]
Thanks, I've tested everything today - works like a charm :)
