### ISSUE TITLE
Parameter `--user-dict` is not recognized

### ISSUE THREAD

**Issue by romanr** [redmine-gitlab-migrator/redmine-gitlab-migrator#25]
I don't know if it's a problem with documentation or it just don't work:

```
migrate-rg issues --redmine-key .... --gitlab-key ...  <url> <url> \
--user-dict userdict.yaml --project-members-only --check
```
Output:
```
migrate-rg: error: unrecognized arguments: --user-dict userdict.yaml --project-members-only
```

**Comment by Danamir** [comment]
It works only in 1.0.3, ie. by cloning the git repo. It doesn't work if you simply do a pip install (which gets the 1.0.2 as of today).

**Comment by hkato** [comment]
ref. #46 #47 

Cc: @scambra you can close this issue.
