### ISSUE TITLE
Gitlab v3 -> v4 api possible solution

### ISSUE THREAD

**Issue by thomas955** [redmine-gitlab-migrator/redmine-gitlab-migrator#34]
Hi,

after digging a bit into, i discovered to change v3 api namespace to v4 only is not enough. (#31)
I also had to change the return from get_id former "id". "id" is the global issue ID and not the project related "iid". So this "id" and cannot be used if any issue was created in gitlab before. Otherwise it will raise an exception cause, the issue_url["id"] is pointing to the global id number and not to the corresponding project issue id.

How do i can create a pull request directly? I dont want to fork this project again.

**Comment by scambra** [comment]
pull requests needs to fork, you can edit file in github to send pull request and it will create fork, or you can fork, clone, push to new branch and then create pull request

**Comment by thomas955** [comment]
Ok ill do so.
I currently try to fix --keep-id also, maybe will take some more time.

**Comment by scambra** [comment]
You have access, so you can push without pull request

**Comment by sdinot** [comment]
I am facing this issue. Is there any news about it?

**Comment by thomas955** [comment]
https://github.com/redmine-gitlab-migrator/redmine-gitlab-migrator/pull/35

Im currently doing my migration too, and still testing if all things work like expected.
This pull request should help you, nearly the same things i fixed in my version.

**Comment by sdinot** [comment]
Thanks a lot. The code provided by the pull request almost works (issues are created), but the users match fails. I just opened an issue about it #36.

**Comment by sdinot** [comment]
Finally, the code provided in the pull request works fine. The reason of the fail was a wrong Redmine API key as I explained it in #36.

**Comment by flashpixx** [comment]
Is there any timeline to integrate the pull request into the current master branch?

**Comment by nelo-digitalagentur** [comment]
+1

**Comment by AdamN1** [comment]
Please check master branch it should work with gitlab api v4

**Comment by HontoNoRoger** [comment]
Can probably be closed as well after #46 is done?
This should fix the problem for people coming here and installing the tool with `pip`.
