### ISSUE TITLE
--user-dict user name format unclear

### ISSUE THREAD

**Issue by maramend** [redmine-gitlab-migrator/redmine-gitlab-migrator#44]
Hi,

I want to use --user-dict to assign the proper users which differs between our redmine and gitlab installation.

Even if I use --user-dict I get a lot of warnings:

`WARNING: Redmine issue #12623 assignee is anonymous. gitlab assinee is attributed to current admin`

or

`WARNING: Redmine user {'id': 565, 'name': 'Heidi Fischer'} is unknown, attribute note to current admin`

No I'm wondering about the proper fromat of my mapping file. I assumed the following format:

`Heidi Fischer: hfischer`

whereas the gitlab username matches the one visible in https://gitlab.instance/profile/account. However, the proper redmine username is not clear to me, since for log in to the redmine instance the username is `fischer.heidi `(lastname.firstname) but activites in Redmine are labeled with `Heidi Fischer` (firstnam lastname). The latter is also shown up when calling https://redmine.instance/users/565.

In any case, I'm not able to get rid of the warnings :-(

Btw., I don't have access to the installation of the redmine and gitlab instance.

**Comment by scambra** [comment]
For redmine you must It uses login field for redmine, which is unique, although redmine displays Firstname Lastname to users.
