### ISSUE TITLE
Tool version on PyPi too old

### ISSUE THREAD

**Issue by HontoNoRoger** [redmine-gitlab-migrator/redmine-gitlab-migrator#46]
When using the `pip install` command to retrieve the tool you'll only get version 1.0.2 which doesn't work with APIv4 in current GitLab versions. Instead it uses APIv3 which seems to not be available in GitLab anymore.

I recommend setting a new version tag on the current master branch state since it seems to run quite well with current GitLab installations. Will this update the PyPi version automatically as well?

**Comment by hkato** [comment]
Maybe PyPI access permission is not taken over yet > @scambra @JocelynDelalande 

How about this

```sh
$ pip install git+https://github.com/redmine-gitlab-migrator/redmine-gitlab-migrator
```

cf. https://pip.pypa.io/en/latest/reference/pip_install/#git

**Comment by JocelynDelalande** [comment]
> Maybe PyPI access permission is not taken over yet > @scambra @JocelynDelalande

I think you are right ; @scambra @AdamN1 could you confirm that you do not have access to pypi for https://pypi.org/project/redmine-gitlab-migrator/ ?

**Comment by scambra** [comment]
Yes, I don't have access to pypi, I didn't have a user. I have added v1.0.3 release and tag 
Homepage for project in pypi.org is wrong (https://github/oasiswork/migrate-redmine-to-gitlab/), I don't know if it matters

**Comment by hkato** [comment]
How about adding pip install latest development version from gitlab.com.

**Comment by JocelynDelalande** [comment]
The pypi account is handled by pypi *oasiswork-devs* account, which I do no longer have access to.

@n11c : do you still have access to this account ? If so, could you transfer  over https://pypi.org/project/redmine-gitlab-migrator/  to https://pypi.org/user/scambra/ ? If not, who should we contact ?

Thanks by advance :pray:

**Comment by n11c** [comment]
Hey @JocelynDelalande, long time ;)

I managed to get access to that account. @scambra you should have received an invite to join the Pypi project as owner. let me know if not.  
Feel free to remove oasiswork-devs access once you're all setup.

All the best with this project!

**Comment by scambra** [comment]
Hi, I have access now to pypi and uploaded 1.0.3.
@thomas955, @AdamN1 do you want to have access to pypi?

**Comment by AdamN1** [comment]
> Hi, I have access now to pypi and uploaded 1.0.3.
> @thomas955, @AdamN1 do you want to have access to pypi?

Yes, it will be easier to retrieve access if somebody will be missing.

**Comment by scambra** [comment]
Ok, @AdamN1 do you have user in pypi.org? I need username to invite you
