### ISSUE TITLE
The option --no-verify do not exist

### ISSUE THREAD

**Issue by Dauliac** [redmine-gitlab-migrator/redmine-gitlab-migrator#47]
Hello,
The `README.md` option `--no-verify` doesn't exist in the code.

Nice day.

**Comment by Manzey** [comment]
Clone the repo and install the module via setup.py instead of pip.
That worked for me 👍

**Comment by hkato** [comment]
ref. #46 

 or directly pip install from github.

Cc: @scambra you can close this issue?
